# Generated by Django 4.1.2 on 2022-10-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[('1', 'G10'), ('2', 'G11'), ('3', 'G12')], default=1),
            preserve_default=False,
        ),
    ]
