# Generated by Django 4.1.2 on 2022-10-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_subject_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', 'G10'), ('2', 'G11'), ('3', 'G12')], default=1),
        ),
    ]
